/**
 * In-memory fixture set used while IS_DEPLOYED=false. The shapes match
 * what the contract's view methods return (after JSON parsing and
 * wire-type coercion). The mock layer exercises the same Service
 * interface so flipping the toggle requires zero page-level changes.
 *
 * Burn text is intentionally sharp but stays inside PRODUCT.md's "lab-grade
 * combative" register. No emoji in any string. No em-dashes.
 */
import type {
  Battle,
  Combatant,
  Dispute,
  Stats,
  Burn,
  Verdict,
  VerdictPartial,
  WriteResult,
} from './types'

const now = () => Math.floor(Date.now() / 1000)

const addresses = {
  cinder:  '0x14dC79A4F5b80496c4A3f9c00e06f1a44b99559955',
  hex:     '0x9aF2c3B7e1A4d5f8b2E0aC9d1f4b6E8a2c5D7F9b1',
  pyro:    '0x7b3E5d1a9C8f2B4d6E0a1c3F5b7d9E2a4c6F8B0d',
  voltaic: '0x2c4A6e8b0d2F4a6c8E0a2c4F6b8d0E2a4c6F8B0d',
  embers:  '0x5e7C9a1b3D5f7A9c1E3a5C7f9B1d3E5a7C9F1B3d',
  ash:     '0x3a5C7e9b1D3f5A7c9E1a3C5f7B9d1E3a5C7F9B1d',
}

function score(s: {
  wit: number; originality: number; burn: number; rhyme: number; topicality: number
}): Burn['scores'] {
  const total = s.wit + s.originality + s.burn + s.rhyme + s.topicality
  return { ...s, total }
}

const burnA: Burn = {
  combatant: addresses.cinder,
  text: 'Your standup is so cold the room asks for a jacket. You write jokes like they were generated by committee. Three rooms of feedback and not one honest laugh.',
  context_url: '',
  scores: score({ wit: 14, originality: 13, burn: 15, rhyme: 10, topicality: 16 }),
  submitted_at: now() - 7400,
}

const burnB: Burn = {
  combatant: addresses.hex,
  text: 'I have seen better pacing on a DMV form. You rhyme with the desperation of someone paying rent with applause. The only thing you are burning is the audiences evening.',
  context_url: '',
  scores: score({ wit: 16, originality: 15, burn: 17, rhyme: 13, topicality: 18 }),
  submitted_at: now() - 6100,
}

const emptyVerdict = (battle_id: number): Verdict => ({
  battle_id,
  winner: '',
  loser: '',
  margin: 0,
  reasoning: '',
  judged_at: 0,
  judge_count: 0,
})

export const MOCK_BATTLES: Battle[] = [
  {
    id: 12,
    topic: 'Why Web3 influencers should disclose paid posts',
    creator: addresses.cinder,
    opponent: addresses.hex,
    state: 'resolved',
    stake: 10_000_000_000_000_000,
    created_at: now() - 7400,
    burns: [burnA, burnB],
    verdict: {
      battle_id: 12,
      winner: addresses.hex,
      loser: addresses.cinder,
      margin: 11,
      reasoning:
        'Higher burn and topicality scores. Opponent named the audiences time, which landed harder than a generic jab.',
      judged_at: now() - 3200,
      judge_count: 3,
    },
  },
  {
    id: 11,
    topic: 'Hot takes on cold brew economics',
    creator: addresses.pyro,
    opponent: addresses.voltaic,
    state: 'resolved',
    stake: 5_000_000_000_000_000,
    created_at: now() - 86_400,
    burns: [
      {
        combatant: addresses.pyro,
        text: 'You charge twelve dollars for bean water and call it innovation. The margin is a hostage note to your landlord.',
        context_url: '',
        scores: score({ wit: 17, originality: 16, burn: 18, rhyme: 11, topicality: 18 }),
        submitted_at: now() - 84_000,
      },
      {
        combatant: addresses.voltaic,
        text: 'Bitter because nobody is queueing for what you brew. Cold and bitter. Same as your career trajectory.',
        context_url: '',
        scores: score({ wit: 15, originality: 14, burn: 16, rhyme: 12, topicality: 17 }),
        submitted_at: now() - 82_000,
      },
    ],
    verdict: {
      battle_id: 11,
      winner: addresses.pyro,
      loser: addresses.voltaic,
      margin: 6,
      reasoning: 'Margin of 6 across all five dimensions. The deciding factor was topicality — pyro stayed closer to the roast register.',
      judged_at: now() - 80_000,
      judge_count: 3,
    } satisfies Verdict,
  },
  {
    id: 10,
    topic: 'If frameworks had a roast of themselves',
    creator: addresses.embers,
    opponent: addresses.ash,
    state: 'disputed',
    stake: 10_000_000_000_000_000,
    created_at: now() - 172_800,
    burns: [
      {
        combatant: addresses.embers,
        text: 'You write CSS like you are negotiating with a hostage taker. Every selector a treaty. None of them honored.',
        context_url: '',
        scores: score({ wit: 13, originality: 12, burn: 14, rhyme: 10, topicality: 13 }),
        submitted_at: now() - 170_000,
      },
      {
        combatant: addresses.ash,
        text: 'You ship a JS framework every six months and call each one a paradigm shift. They are all the same bug with new marketing.',
        context_url: '',
        scores: score({ wit: 15, originality: 14, burn: 15, rhyme: 9, topicality: 14 }),
        submitted_at: now() - 168_000,
      },
    ],
    verdict: {
      battle_id: 10,
      winner: addresses.ash,
      loser: addresses.embers,
      margin: 5,
      reasoning: 'Tighter pivot on industry practice. Margin thin enough to invite challenge.',
      judged_at: now() - 165_000,
      judge_count: 3,
    },
  },
  {
    id: 9,
    topic: 'Open duel. Topic of your choice.',
    creator: addresses.cinder,
    opponent: '',
    state: 'open',
    stake: 10_000_000_000_000_000,
    created_at: now() - 600,
    burns: [],
    verdict: emptyVerdict(9),
  },
  {
    id: 8,
    topic: 'Roast my LinkedIn bio. I dare you.',
    creator: addresses.pyro,
    opponent: '',
    state: 'open',
    stake: 5_000_000_000_000_000,
    created_at: now() - 1800,
    burns: [],
    verdict: emptyVerdict(8),
  },
  {
    id: 7,
    topic: 'Best roast of AI influencers. Go.',
    creator: addresses.hex,
    opponent: addresses.voltaic,
    state: 'both_burned',
    stake: 10_000_000_000_000_000,
    created_at: now() - 12_000,
    burns: [
      {
        combatant: addresses.hex,
        text: 'You post a screenshot of a chatbot and call it a thought. Engagement is up. Discourse is down. Congrats.',
        context_url: '',
        scores: { wit: 0, originality: 0, burn: 0, rhyme: 0, topicality: 0, total: 0 },
        submitted_at: now() - 7000,
      },
      {
        combatant: addresses.voltaic,
        text: 'You made a thread about vibes and called it a thesis. The AI in your bio stands for Already Incoherent.',
        context_url: '',
        scores: { wit: 0, originality: 0, burn: 0, rhyme: 0, topicality: 0, total: 0 },
        submitted_at: now() - 5500,
      },
    ],
    verdict: emptyVerdict(7),
  },
  {
    id: 6,
    topic: 'Why your NFT roadmap is a screenshot',
    creator: addresses.ash,
    opponent: addresses.embers,
    state: 'resolved',
    stake: 10_000_000_000_000_000,
    created_at: now() - 260_000,
    burns: [
      {
        combatant: addresses.ash,
        text: 'You drew the roadmap in Figma and called it a vision. The deliverable is a JPEG and the J stands for Just Enough.',
        context_url: '',
        scores: score({ wit: 16, originality: 15, burn: 17, rhyme: 11, topicality: 18 }),
        submitted_at: now() - 258_000,
      },
      {
        combatant: addresses.embers,
        text: 'You minted a toaster and called it culture. The holders are twelve friends and a wallet you control.',
        context_url: '',
        scores: score({ wit: 15, originality: 14, burn: 16, rhyme: 12, topicality: 17 }),
        submitted_at: now() - 256_000,
      },
    ],
    verdict: {
      battle_id: 6,
      winner: addresses.ash,
      loser: addresses.embers,
      margin: 3,
      reasoning: 'Narrow margin. Judges noted stronger topicality tied to roadmap artifacts.',
      judged_at: now() - 254_000,
      judge_count: 3,
    },
  },
]

export const MOCK_COMBATANTS: Record<string, Combatant> = {
  [addresses.cinder]: {
    addr: addresses.cinder,
    wins: 7, losses: 3, draws: 1,
    reputation: 67, total_burns: 11,
    best_score: 68, best_score_battle: 12,
  },
  [addresses.hex]: {
    addr: addresses.hex,
    wins: 12, losses: 4, draws: 0,
    reputation: 82, total_burns: 16,
    best_score: 78, best_score_battle: 12,
  },
  [addresses.pyro]: {
    addr: addresses.pyro,
    wins: 5, losses: 2, draws: 1,
    reputation: 71, total_burns: 8,
    best_score: 74, best_score_battle: 11,
  },
  [addresses.voltaic]: {
    addr: addresses.voltaic,
    wins: 3, losses: 6, draws: 0,
    reputation: 41, total_burns: 9,
    best_score: 66, best_score_battle: 11,
  },
  [addresses.embers]: {
    addr: addresses.embers,
    wins: 4, losses: 5, draws: 0,
    reputation: 48, total_burns: 9,
    best_score: 64, best_score_battle: 6,
  },
  [addresses.ash]: {
    addr: addresses.ash,
    wins: 9, losses: 2, draws: 0,
    reputation: 79, total_burns: 11,
    best_score: 77, best_score_battle: 6,
  },
}

export const MOCK_DISPUTES: Dispute[] = [
  {
    id: 1,
    battle_id: 10,
    raised_by: addresses.embers,
    reason:
      'Reasoning cited topicality over burn intensity. The decisive dimension for a roast should weight burn, not topicality.',
    raised_at: now() - 160_000,
    status: 'open',
    prior_winner: addresses.ash,
    resolved_at: 0,
  },
]

export function computeStats(): Stats {
  const battles = MOCK_BATTLES
  const resolved = battles.filter((b) => b.state === 'resolved').length
  const disputed = battles.filter((b) => b.state === 'disputed').length
  return {
    total_battles: battles.length,
    resolved_battles: resolved,
    disputed_battles: disputed,
    open_battles:
      MOCK_BATTLES.filter((b) => b.state === 'open' || b.state === 'both_burned' || b.state === 'both_joined').length,
    total_combatants: Object.keys(MOCK_COMBATANTS).length,
    total_disputes: MOCK_DISPUTES.length,
  }
}

/**
 * Backend interface used by the service layer when IS_DEPLOYED=false.
 * Mirrors the contract's public read/write surface so flipping the toggle
 * to true drops the user straight into live consensus without page changes.
 */
export const mockBackend = {
  // Reads
  async getStats(): Promise<Stats> {
    return computeStats()
  },
  async getRecentBattles(
    limit: number,
    offset: number,
  ): Promise<{ battles: Battle[]; total: number }> {
    const sorted = [...MOCK_BATTLES].sort((a, b) => b.id - a.id)
    const sliced = sorted.slice(offset, offset + limit)
    return { battles: sliced, total: MOCK_BATTLES.length }
  },
  async getBattle(id: number): Promise<Battle | null> {
    return MOCK_BATTLES.find((b) => b.id === id) ?? null
  },
  async getCombatant(addr: string): Promise<Combatant | null> {
    return MOCK_COMBATANTS[addr] ?? null
  },
  async getDispute(id: number): Promise<Dispute | null> {
    return MOCK_DISPUTES.find((d) => d.id === id) ?? null
  },

  // Writes (in-memory; never persisted; used to demo the UI flow)
  async createBattle(
    _account: any,
    topic: string,
    _stakeWei: bigint,
  ): Promise<WriteResult> {
    return { hash: `0xmock${Math.random().toString(16).slice(2, 14)}` }
  },
  async joinBattle(_account: any, _battleId: number): Promise<WriteResult> {
    return { hash: `0xmock${Math.random().toString(16).slice(2, 14)}` }
  },
  async submitBurn(
    _account: any,
    _battleId: number,
    _text: string,
    _url: string,
  ): Promise<WriteResult> {
    return { hash: `0xmock${Math.random().toString(16).slice(2, 14)}` }
  },
  async judgeBattle(_account: any, _battleId: number): Promise<WriteResult> {
    return { hash: `0xmock${Math.random().toString(16).slice(2, 14)}` }
  },
  async raiseDispute(
    _account: any,
    _battleId: number,
    _reason: string,
  ): Promise<WriteResult> {
    return { hash: `0xmock${Math.random().toString(16).slice(2, 14)}` }
  },
  async resolveDispute(_account: any, _disputeId: number): Promise<WriteResult> {
    return { hash: `0xmock${Math.random().toString(16).slice(2, 14)}` }
  },
}